# Generated by Django 4.0.5 on 2022-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=120, verbose_name='Notification Message')),
                ('creation_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
