# Generated by Django 4.0.4 on 2022-06-13 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_merge_20220611_1908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notified_developer', to=settings.AUTH_USER_MODEL, verbose_name='notified developer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_notified', to='job.job', verbose_name='job notified'),
        ),
    ]
