# Generated by Django 4.0.4 on 2022-06-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_merge_20220611_1908'),
        ('notification', '0002_notification_developer_notification_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job', verbose_name='job notified'),
        ),
    ]
