# Generated by Django 4.0.5 on 2022-06-11 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Job title')),
                ('creation_time', models.DateField(auto_now_add=True)),
                ('modification_time', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('finished', 'finished')], max_length=12)),
                ('applied_developers', models.ManyToManyField(related_name='applied_developers', to=settings.AUTH_USER_MODEL, verbose_name='Applied developers')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to=settings.AUTH_USER_MODEL, verbose_name='Job owner')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_developer', to=settings.AUTH_USER_MODEL, verbose_name='Accepted developer')),
                ('tags', models.ManyToManyField(to='tag.tag')),
            ],
        ),
    ]
