# Generated by Django 4.0.4 on 2022-06-11 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='NO Description', verbose_name='job description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='applied_developers',
            field=models.ManyToManyField(null=True, related_name='applied_developers', to=settings.AUTH_USER_MODEL, verbose_name='Applied developers'),
        ),
        migrations.AlterField(
            model_name='job',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_developer', to=settings.AUTH_USER_MODEL, verbose_name='Accepted developer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='open', max_length=12),
        ),
    ]
