# Generated by Django 4.0.4 on 2022-06-11 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_job_description_alter_job_applied_developers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to=settings.AUTH_USER_MODEL, verbose_name='Job owner'),
        ),
    ]
