# Generated by Django 4.0.5 on 2022-06-11 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_created_by'),
        ('job', '0003_alter_job_developer'),
    ]

    operations = [
    ]
